on:
  push:
    branches:
    - main
jobs:
  BuildBin:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.0
        target: esp32
        path: '.'
        command: idf.py build
    - name: upload artifact
      uses: actions/upload-artifact@v3
      with:
        path: |
          build/MorningRing.bin
          build/version.txt
  UploadOSS:
    runs-on: ubuntu-latest
    needs: BuildBin

    steps:
    - name: Download OSSutil
      run: wget ${{ vars.OSSUTIL_DOWNLOADURL }} -O ossutil
    - run: chmod +x ossutil
    - name: Set ossutilconfig
      run: echo ${{ secrets.OSSUTILCONFIG }} > ossutilconfig
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        path: ./artifacts
    - run: echo "::notice Version `cat artifacts/version.txt` will upload"
    - run: ./ossutil cp ./artifacts/MorningRing.bin oss://morningring/MorningRing.bin -y
    - run: ./ossutil cp ./artifacts/MorningRing.bin oss://morningring/MorningRing.`cat artifacts/version.txt`.bin -y
    - run: echo "::notice Version `cat artifacts/version.txt` uploaded"
